alertHeader() ::= <<
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login Page</title>
    <link rel="shortcut icon" href="https://1000hz.github.io/bootstrap-validator/assets/ico/favicon.png">
    <link rel="stylesheet" href="/files/templates/validator/bootstrap.css" />
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <link href="/files/templates/custom.css" type="text/css" rel="stylesheet">
>>