changepwdHeader() ::= <<
     <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <title>Register Page</title>
     <link rel="shortcut icon" href="https://1000hz.github.io/bootstrap-validator/assets/ico/favicon.png">
     <link rel="stylesheet" href="/files/templates/validator/bootstrap.css" />
     <link rel="stylesheet" href="/files/templates/validator/formValidation.css" />
     <script type="text/javascript" src="/files/templates/validator/jquery.min.js"></script>
     <script type="text/javascript" src="/files/templates/validator/bootstrap.min.js"></script>
     <script type="text/javascript" src="/files/templates/validator/formValidation.js"></script>
     <script type="text/javascript" src="/files/templates/validator/bootstrap.js"></script>
     <script type="text/javascript" src="/files/templates/changepwd.js"></script>
     <link href="/files/templates/custom.css" type="text/css" rel="stylesheet">
 >>