loginHeader() ::= <<
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login page for web mail</title>
    <link rel="shortcut icon" href="https://1000hz.github.io/bootstrap-validator/assets/ico/favicon.png">
    <link href="/files/templates/fromweb/bootstrap.min.css" rel="stylesheet">
    <link href="/files/templates/signin.css" rel="stylesheet">

    <!-- My custom styles for Login Page -->
    <link href="/files/templates/custom.css" type="text/css" rel="stylesheet">
    <style id="style-1-cropbar-clipper">
    .en-markup-crop-options {
        top: 18px !important;
        left: 50% !important;
        margin-left: -100px !important;
        width: 200px !important;
        border: 2px rgba(255, 255, 255, .38) solid !important;
        border-radius: 4px !important;
    }

    .en-markup-crop-options div div:first-of-type {
        margin-left: 0px !important;
    }
</style>
>>